---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/news
  label: News
  create: documents
  match: "**/*"
  templates:
  - news
- type: directory
  path: content/videos
  label: Videos
  create: documents
  match: "**/*"
  templates:
  - video
upload_dir: content/images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.2
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.2
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.2
